# Generated by Django 5.1.3 on 2024-12-10 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_employee_date_joined_employee_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_active',
        ),
    ]
