# Generated by Django 5.1.3 on 2024-12-10 07:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_employee_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
