# Generated by Django 5.1.3 on 2024-12-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_employee_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
