# Generated by Django 5.1.3 on 2024-12-14 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_alter_employee_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demand',
            options={'ordering': ['-date'], 'verbose_name': 'Demand', 'verbose_name_plural': 'Demands'},
        ),
    ]
