# Generated by Django 5.0.4 on 2025-01-04 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_alter_demand_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLogoutActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField()),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('login_latitude', models.FloatField()),
                ('login_longitude', models.FloatField()),
                ('logout_latitude', models.FloatField(blank=True, null=True)),
                ('logout_longitude', models.FloatField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.employee')),
            ],
        ),
    ]
