# Generated by Django 5.0.4 on 2025-01-08 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0010_alter_loginlogoutactivity_login_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginlogoutactivity',
            name='logout_latitude',
        ),
        migrations.RemoveField(
            model_name='loginlogoutactivity',
            name='logout_longitude',
        ),
        migrations.RemoveField(
            model_name='loginlogoutactivity',
            name='logout_time',
        ),
    ]
